version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus1
    restart: unless-stopped
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9091:9090
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge